### PR TITLE
Export certificate of computation to PNG image

### PR DESCRIPTION
**Pull request by Delizald**
Added a small export to PNG button at the bottom of the certificate.
@AenBleidd assigned to me this task a long long time ago but unfortunately life gets in the way and I tend to procrastinate a lot :(

I'll work on sharing the certificate on social media after this one.

boinc-computation-certificate_](https://github.com/BOINC/boinc-site/assets/5884968/5c2acc52-81ca-47c8-944f-02477baef1c2)

### CODE REVIEW

**Comment by AenBleidd** [comment]
@davidpanderson, could you please review and test this PR?

**Comment by davidpanderson** [comment]
Nice! I added the following:
function export_to_img() {
  echo '
  **<script src="html2canvas.min.js"></script>**
 ...

**Comment by davidpanderson** [comment]
BTW, we could add this feature to the BOINC web code,
for the certificates on project web sites.

**Comment by AenBleidd** [comment]
@davidpanderson, sounds nice! Could you please do that?

**Comment by davidpanderson** [comment]
Done.

**Pull request merged**
